[project]
name = "ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tensorflow==2.19.0",
    "matplotlib>=3.10.3",
    "numpy>=2.1.3",
    "keras>=3.10.0",
    "black>=25.1.0",
    "ipykernel>=6.29.5",
]
